#ifndef UNITY_CONFIG_H_
#define UNITY_CONFIG_H_

#define UNITY_INCLUDE_CONFIG_H
#define UNITY_INCLUDE_DOUBLE
#define UNITY_DOUBLE_PRECISION 0.1
#define UNITY_INCLUDE_PRINT_FORMATTED

#endif // UNITY_CONFIG_H_
